const Database = require("better-sqlite3");
const { Pool } = require("pg");

const SQLITE_PATH = process.argv[2] || "medbank.db";
if (!process.env.PG_URL) { console.error("Set PG_URL first"); process.exit(1); }

const q = (n) => '"' + String(n).replace(/"/g, '""') + '"';
const pgType = (t) => {
  t = (t || "").toUpperCase();
  if (t.includes("INT")) return "BIGINT";
  if (/REAL|FLOA|DOUB/.test(t)) return "DOUBLE PRECISION";
  if (t.includes("BLOB")) return "BYTEA";
  return "TEXT";
};
const simpleDefault = (d) =>
  d != null && /^('.*'|-?\d+(\.\d+)?)$/.test(String(d).trim()) ? String(d).trim() : null;

(async () => {
  const lite = new Database(SQLITE_PATH, { readonly: true, fileMustExist: true });
  const pool = new Pool({ connectionString: process.env.PG_URL, ssl: { rejectUnauthorized: false } });
  const tables = lite
    .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
    .all().map((r) => r.name);

  const report = [];
  for (const t of tables) {
    const cols = lite.prepare(`PRAGMA table_info(${q(t)})`).all();
    const pks = cols.filter((c) => c.pk > 0).sort((a, b) => a.pk - b.pk);
    const looseCols = new Set();
    for (const c of cols) {
      const pt = pgType(c.type);
      if (pt === "BIGINT" || pt === "DOUBLE PRECISION") {
        const allowed = pt === "BIGINT" ? "'integer','null'" : "'integer','real','null'";
        const bad = lite.prepare(`SELECT 1 FROM ${q(t)} WHERE typeof(${q(c.name)}) NOT IN (${allowed}) LIMIT 1`).get();
        if (bad) { looseCols.add(c.name); console.log(`  note: ${t}.${c.name} has mixed values, stored as TEXT`); }
      }
    }
    const identityCol =
      pks.length === 1 && !looseCols.has(pks[0].name) && (cols.find((c) => c.name === pks[0].name).type || "").toUpperCase() === "INTEGER"
        ? pks[0].name : null;

    const defs = cols.map((c) => {
      if (c.name === identityCol) return `${q(c.name)} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
      let s = `${q(c.name)} ${looseCols.has(c.name) ? "TEXT" : pgType(c.type)}`;
      if (c.notnull) s += " NOT NULL";
      const d = simpleDefault(c.dflt_value);
      if (d !== null) s += ` DEFAULT ${d}`;
      return s;
    });
    if (!identityCol && pks.length) defs.push(`PRIMARY KEY (${pks.map((p) => q(p.name)).join(", ")})`);

    await pool.query(`DROP TABLE IF EXISTS ${q(t)} CASCADE`);
    await pool.query(`CREATE TABLE ${q(t)} (${defs.join(", ")})`);

    const names = cols.map((c) => q(c.name)).join(", ");
    const batch = Math.max(1, Math.min(500, Math.floor(60000 / cols.length)));
    const rows = lite.prepare(`SELECT ${names} FROM ${q(t)}`).raw().all();
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      for (let i = 0; i < rows.length; i += batch) {
        const chunk = rows.slice(i, i + batch);
        const params = [];
        const ph = chunk.map((row) =>
          "(" + row.map((v) => { params.push(v); return "$" + params.length; }).join(",") + ")"
        ).join(",");
        await client.query(`INSERT INTO ${q(t)} (${names}) VALUES ${ph}`, params);
      }
      await client.query("COMMIT");
    } catch (e) {
      await client.query("ROLLBACK");
      throw new Error(`Table ${t}: ${e.message}`);
    } finally { client.release(); }

    if (identityCol) {
      await pool.query(
        `SELECT setval(pg_get_serial_sequence($1, $2), COALESCE(MAX(${q(identityCol)}), 1), MAX(${q(identityCol)}) IS NOT NULL) FROM ${q(t)}`,
        [q(t), identityCol]
      );
    }
    await pool.query(`ALTER TABLE ${q(t)} ENABLE ROW LEVEL SECURITY`);

    const src = lite.prepare(`SELECT COUNT(*) c FROM ${q(t)}`).get().c;
    const dst = Number((await pool.query(`SELECT COUNT(*) c FROM ${q(t)}`)).rows[0].c);
    report.push({ table: t, sqlite: src, postgres: dst, ok: src === dst ? "OK" : "MISMATCH" });
    console.log(`${t}: ${dst}/${src} rows`);
  }
  console.table(report);
  await pool.end();
  lite.close();
})().catch((e) => { console.error("FAILED:", e.message); process.exit(1); });
